version: '3.1'

services:
  blockchaindemo:
    container_name: blockchaindemo
    image: kelvinator07/blockchaindemo:v1.0.0
    build: .
#    restart: always
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      - DB_SERVER=postgres-db
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/blockchaindb  # container-name:port/db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - SPRING_SQL_INIT_MODE=always

  # Database Service (Postgres)
  postgres-db:
    image: postgres
    container_name: postgres-db
    environment:
      - POSTGRES_DB=blockchaindb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: